/**
 * (c) 2003-2014 MuleSoft, Inc. The software in this package is published under
 * the terms of the CPAL v1.0 license, a copy of which has been included with this
 * distribution in the LICENSE.md file.
 */

/**
 * This file was automatically generated by the Mule Development Kit
 */
package org.mule.modules.handshake;

import org.junit.Test;
import org.mule.tck.junit4.FunctionalTestCase;

public class HandshakeConnectorNamespaceTest extends FunctionalTestCase {

    @Override
    protected String getConfigResources() {
        return "mule-config.xml";
    }

    @Test
    public void forceXMLParse() throws Exception {
        // If anything is wrong on the XML, it should fail
    }

}
